[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "node scripts/init_prod_db.js && node src/server.js"
