import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
    en: {
        nav: {
            shop: 'Shop',
            collections: 'Collections',
            new_arrivals: 'New Arrivals',
            about: 'About',
            search: 'Search',
            lookbook: 'Lookbook',
            home: 'Home',
        },
        hero: {
            badge: 'New Winter Collection 2025',
            title: 'Elevate Your Style with',
            subtitle: 'Discover premium sweaters designed for those who see the world differently. Comfort meets avant-garde aesthetics.',
            btn_shop: 'Shop Now',
            btn_lookbook: 'Watch Lookbook',
        },
        home: {
            collections_title: 'Collections',
            explore: 'Explore',
            lifestyle_title: 'Beyond',
            lifestyle_subtitle: 'Clothing.',
            lifestyle_text: 'Visualmind is not just a brand; it\'s a perspective. We believe that what you wear should be as complex and beautiful as the mind that chooses it.',
            lifestyle_btn: 'Our Vision',
            newsletter_title: 'Join the Vision',
            newsletter_text: 'Subscribe to receive early access to new drops and exclusive member-only collections.',
            newsletter_placeholder: 'Enter your email',
            newsletter_btn: 'Subscribe',
        },
        collections: {
            title: 'Exclusive',
            accent: 'Collections',
            subtitle: 'Dive into our curated universes. Each collection is a limited-run exploration of style, material, and vision.',
            items: 'Items',
            btn_view: 'View Collection',
            back: 'Back to Collections',
        },
        new_arrivals: {
            badge: 'Exclusive Drop',
            title: 'THE',
            title_accent: 'NEW',
            title_end: 'STANDARD.',
            subtitle: 'Explore pieces that merge technological avant-garde with ancestral craftsmanship.',
            edition: 'Edition 001/100',
            best_in_show: 'BEST IN SHOW',
            btn_add: 'Add To Bag',
            btn_details: 'View Details',
        },
        shop: {
            title: 'The Collection',
            subtitle: 'Explore our latest drops and timeless essentials. Designed for the modern visionary.',
            filter_all: 'All Items',
            filter_bestsellers: 'Best Sellers',
            cat_anime: 'Anime',
            cat_caricaturas: 'Cartoons',
            cat_videojuegos: 'Video Games',
            cat_deportes: 'Sports',
            cat_sanvalentin: 'Valentine\'s',
            cat_halloween: 'Halloween',
            cat_fiestas_patrias: 'National Holidays',
            filter_title: 'Filters',
            filter_categories: 'Categories',
            filter_price: 'Price Range',
            search_placeholder: 'Search...',
            price_all: 'Price: All',
            price_low: '$0 - $50',
            price_mid: '$50 - $100',
            price_high: '$100+',
            no_results: 'No products found with those filters.',
        },
        product: {
            select_size: 'Select Size',
            select_color: 'Select Color',
            add_to_bag: 'Add To Bag',
            reviews: 'Reviews',
            description: 'Description',
        },
        about: {
            title: 'Our Story',
            vision_title: 'The Vision',
            vision_text: 'Visualmind was born at the intersection of digital art and physical garments. We create pieces that challenge traditional silhouettes while maintaining the highest standards of comfort.',
            values_title: 'Our Values',
            value_1_title: 'Avant-Garde',
            value_1_text: 'Pushing boundaries in design.',
            value_2_title: 'Quality',
            value_2_text: 'Only the finest materials.',
            value_3_title: 'Community',
            value_3_text: 'For those who see differently.',
        },
        cart: {
            title: 'Shopping Bag',
            empty: 'Your bag is empty',
            subtotal: 'Subtotal',
            checkout: 'Checkout',
            back: 'Back to Shopping',
            items_count: 'items',
            qty: 'Qty',
        },
        checkout: {
            title: 'Checkout',
            shipping: 'Shipping Detail',
            name: 'Full Name',
            email: 'Email Address',
            address: 'Address',
            city: 'City',
            zip: 'Zip Code',
            payment: 'Payment Detail',
            card: 'Card Number',
            expiry: 'Expiry Date',
            summary: 'Order Summary',
            btn_complete: 'Complete Purchase',
        },
        search: {
            close: 'CLOSE',
            placeholder: 'Search for clothes, collections, inspiration...',
            no_results: 'No results found for',
            trending: 'Trending Now',
        },
        lookbook: {
            back: 'BACK TO HOME',
            editorial: 'Editorial',
            the: 'THE',
            chronicles: 'CHRONICLES',
            subtitle: "A curated visual journey through Visualmind's most iconic drops and seasonal narratives.",
            look1: 'Summer in the Line',
            look2: 'Autumn Shadows',
            look3: 'The Goat Series',
            look4: 'Underground Aesthetic',
            look5: 'Cursed Style',
            look6: 'Valentine Drops',
        },
        home_extended: {
            featured_drops: 'Featured Drops',
            signature_pieces: 'Signature Pieces',
            exclusive_release: 'EXCLUSIVE RELEASE',
            desc_prefix: 'Experience luxury with our signature',
            desc_suffix: 'collection. Designed for those who demand excellence in every stitch.',
            btn_explore: 'Explore Product',
            limited_stock: 'LIMITED STOCK',
            limited_time_drop: 'LIMITED TIME DROP',
            seasonal_specials: 'Seasonal Specials',
            seasonal_desc: 'Exclusive collections created for special moments. Available only for a few weeks.',
            view_full_drop: 'View Full Drop',
            visual_experience: 'Visual Experience',
            the_lookbook: 'The Lookbook',
            view_narratives: 'View All Narratives',
            style_01: 'STYLE 01',
            seasonal_aura: 'Seasonal Aura',
            quote: '"Fashion is the armor to survive the reality of everyday life."',
            since: 'Since 2024',
            digital_heritage_1: 'Creating the',
            digital_heritage_2: 'Digital Heritage',
            about_text: "At Visualmind, we believe that clothing is more than fabric—it's a medium for self-expression. We bridge the gap between digital culture and physical reality through meticulously crafted garments.",
            stat_1: 'PREMIUM COTTON',
            stat_2: 'EXCLUSIVE DROPS',
            stat_3: 'SHIPPING READY',
            join_universe: 'Join the Universe',
            join_text: 'Subscribe to get early access to new drops and exclusive member-only offers.',
            subscribe: 'Subscribe',
        },
        shop_extended: {
            collections_group: 'Collections',
            seasonals_group: 'Seasonals',
            price_range: 'Price Range',
            sizes: 'Sizes',
            colors: 'Colors',
            showing: 'Showing',
            of: 'of',
            products: 'products',
            sort_by: 'Sort by:',
            sort_newest: 'Newest First',
            sort_low_high: 'Price: Low to High',
            sort_high_low: 'Price: High to Low',
            no_results_text: "Try adjusting your filters to find what you're looking for.",
            reset_filters: 'Reset All Filters',
        },
        auth: {
            welcome: 'Welcome Back',
            join: 'Join Visualmind',
            login_subtitle: 'Enter your credentials to access your account',
            signup_subtitle: 'Create an account to track orders and save wishlist',
            email: 'Email',
            password: 'Password',
            sign_in: 'Sign In',
            sign_up: 'Sign Up',
            create_account: 'Create Account',
            no_account: "Don't have an account?",
            has_account: "Already have an account?",
            success_create: 'Account created! You are now logged in.',
            error_generic: 'An error occurred.',
        },
        profile: {
            title: 'My Account',
            admin_access: 'Access Admin Panel',
            sign_out: 'Sign Out',
            history: 'Order History',
            loading: 'Loading orders...',
            no_orders: 'No orders found.',
            order_prefix: 'Order #',
            login_prompt: 'Please log in to view your profile.',
            btn_login: 'Login',
            edit_title: 'Edit Profile',
            full_name: 'Full Name',
            email: 'Email',
            save: 'Save Changes',
            saving: 'Saving...',
            update_success: 'Profile updated successfully.',
            update_error: 'Error updating profile.',
        },
        admin: {
            title: 'VM Admin',
            dashboard: 'Dashboard',
            products: 'Products',
            orders: 'Orders',
            settings: 'Settings',
            overview: 'Overview',
            user_label: 'Admin User',
            access_denied: 'Access Denied',
            denied_msg: 'You do not have permission to view this area.',
            go_home: 'Go Home',
            log_out: 'Log Out',
            starting: 'Starting Admin Panel...',
            // Dashboard
            stats_sales: 'Total Sales',
            stats_orders: 'Active Orders',
            stats_customers: 'Total Customers',
            stats_rate: 'Conversion Rate',
            recent_orders: 'Recent Orders',
            low_stock: 'Low Stock Alert',
            table_id: 'Order ID',
            table_customer: 'Customer',
            table_date: 'Date',
            table_status: 'Status',
            table_total: 'Total',
            table_items: 'Items',
            table_action: 'Action',
            stock_left: 'Only {{count}} left',
            // Products
            add_product: 'Add Product',
            edit_product: 'Edit Product',
            search_products: 'Search products...',
            no_products: 'No products found.',
            save_product: 'Save Product',
            saving: 'Saving...',
            confirm_delete: 'Are you sure you want to delete this product?',
            label_title: 'Product Title',
            label_category: 'Category',
            label_subcategory: 'Sub Category',
            label_sku: 'SKU',
            label_stock: 'Stock',
            label_price: 'Price',
            label_image: 'Image URL',
            // Orders
            filter_pending: 'Pending',
            filter_shipped: 'Shipped',
            filter_delivered: 'Delivered',
            // Settings
            settings_title: 'Settings & Permissions',
            admin_mgmt: 'Admin Management',
            admin_desc: 'Grant admin access to other users.',
            promote_title: 'Promote User to Admin',
            promote_desc: 'Enter the email address of a registered user to grant them full access.',
            promote_warn: 'Warning: This grants full control.',
            promote_btn: 'Promote',
            success_promote: 'Success! User is now an Admin.',
            user_not_found: 'User not found.',
            your_profile: 'Your Profile',
            role_label: 'Role',
        },
        common: {
            loading: 'Loading...',
            processing: 'Processing...',
            success: 'Success',
            error: 'Error',
            secure_payment: 'Secure Payment via Stripe',
        },
        footer: {
            follow: 'Follow Us',
            support: 'Support',
            shop: 'Shop',
            privacy: 'Privacy Policy',
            terms: 'Terms of Service',
            rights: 'All rights reserved. Built for the future.',
            desc: 'Elevating pop culture through premium apparel. Designed for the bold and the creative.',
            description: 'Elevating pop culture through premium apparel. Designed for the bold and the creative.',
            shipping: 'Shipping',
            returns: 'Returns',
            links: {
                shipping: 'Shipping',
                returns: 'Returns',
                size_guide: 'Size Guide',
                contact: 'Contact',
            }
        },
        collections_page: {
            back: 'Back to Collections',
            archive_title: 'Visualmind Archive',
            curations: 'Curations',
            view_archive: 'View Archive',
            limited_drop: 'LIMITED DROP',
            anime_sub: 'The Soul of Japanese Art',
            anime_desc: 'Explore our curated selection of high-end anime inspired apparel. Each piece tells a story of craftsmanship and passion.',
            videojuegos_sub: 'Level Up Your Aesthetics',
            videojuegos_desc: 'Where gaming culture meets luxury fashion. Designed for those who appreciate the artistry behind pixels.',
            halloween_title: 'Halloween Drop',
            halloween_sub: 'Limited Seasonal Release',
            halloween_desc: 'A dark, sophisticated take on seasonal wear. Each item is part of a numbered limited series.',
            deportes_sub: 'Elite Performance, Urban Style',
            deportes_desc: 'Bridging the gap between athletic excellence and street-ready sophistication.',
        },
        new_arrivals_page: {
            seasonal_active: 'SEASONAL DROPS ACTIVE',
            next_gen: 'Next Generation',
            desc: 'The latest evolution of Visualmind. Limited pieces, infinite style.',
            fresh_in: 'Fresh In',
            items: 'ITEMS',
            archive_halloween: 'The Archive: Halloween',
            limited_seasonal: 'Limited Seasonal Drop',
            expires: 'EXPIRES IN 14 DAYS',
            coming_soon: 'COMING NEXT MONTH',
            winter_series: 'The Winter Cyberpunk Series',
            winter_desc: 'We are currently finalizing the most ambitious collection in Visualmind history. High-tech fabrics meet avant-garde silhouettes.',
        },
        wishlist_page: {
            empty_title: 'Your Wishlist is Empty',
            empty_desc: 'Save your favorite items here to keep track of what you love.',
            explore: 'Explore Shop',
            title: 'Wishlist',
            count_text: 'You have {{count}} items saved in your list.',
        },
        search_modal: {
            trending_items: ['Outerwear', 'Knitwear', 'Essentials'],
        }
    },
    es: {
        nav: {
            shop: 'Tienda',
            collections: 'Colecciones',
            new_arrivals: 'Novedades',
            about: 'Nosotros',
            search: 'Buscar',
            lookbook: 'Lookbook',
            home: 'Inicio',
        },
        hero: {
            badge: 'Nueva Colección Invierno 2025',
            title: 'Eleva tu Estilo con',
            subtitle: 'Descubre suéteres premium diseñados para quienes ven el mundo de forma diferente. El confort se une a la estética vanguardista.',
            btn_shop: 'Comprar Ahora',
            btn_lookbook: 'Ver Lookbook',
        },
        home: {
            collections_title: 'Colecciones',
            explore: 'Explorar',
            lifestyle_title: 'Más allá de la',
            lifestyle_subtitle: 'Ropa.',
            lifestyle_text: 'Visualmind no es solo una marca; es una perspectiva. Creemos que lo que vistes debe ser tan complejo y hermoso como la mente que lo elige.',
            lifestyle_btn: 'Nuestra Visión',
            newsletter_title: 'Únete a la Visión',
            newsletter_text: 'Suscríbete para recibir acceso anticipado y colecciones exclusivas para miembros.',
            newsletter_placeholder: 'Tu correo electrónico',
            newsletter_btn: 'Suscribirse',
        },
        collections: {
            title: 'Colecciones',
            accent: 'Exclusivas',
            subtitle: 'Sumérgete en nuestros universos seleccionados. Cada colección es una exploración limitada de estilo y visión.',
            items: 'Artículos',
            btn_view: 'Ver Colección',
            back: 'Volver a Colecciones',
        },
        new_arrivals: {
            badge: 'Lanzamiento Exclusivo',
            title: 'EL',
            title_accent: 'NUEVO',
            title_end: 'ESTÁNDAR.',
            subtitle: 'Explora piezas que fusionan la vanguardia tecnológica con la artesanía ancestral.',
            edition: 'Edición 001/100',
            best_in_show: 'LO MEJOR',
            btn_add: 'Añadir al Carrito',
            btn_details: 'Ver Detalles',
        },
        shop: {
            title: 'La Colección',
            subtitle: 'Explora nuestros últimos lanzamientos y básicos atemporales. Diseñado para el visionario moderno.',
            filter_all: 'Todo',
            filter_bestsellers: 'Más Vendidos',
            cat_anime: 'Anime',
            cat_caricaturas: 'Caricaturas',
            cat_videojuegos: 'Videojuegos',
            cat_deportes: 'Deportes',
            cat_sanvalentin: 'San Valentín',
            cat_halloween: 'Halloween',
            cat_fiestas_patrias: 'Fiestas Patrias',
            filter_title: 'Filtros',
            filter_categories: 'Categorías',
            filter_price: 'Rango de Precio',
            search_placeholder: 'Buscar...',
            price_all: 'Precio: Todos',
            price_low: '$0 - $50',
            price_mid: '$50 - $100',
            price_high: '$100+',
            no_results: 'No se encontraron productos con esos filtros.',
        },
        product: {
            select_size: 'Seleccionar Talla',
            select_color: 'Seleccionar Color',
            add_to_bag: 'Añadir a la Bolsa',
            reviews: 'Reseñas',
            description: 'Descripción',
        },
        about: {
            title: 'Nuestra Historia',
            vision_title: 'La Visión',
            vision_text: 'Visualmind nació en la intersección del arte digital y las prendas físicas. Creamos piezas que desafían las siluetas tradicionales.',
            values_title: 'Nuestros Valores',
            value_1_title: 'Vanguardia',
            value_1_text: 'Superando los límites del diseño.',
            value_2_title: 'Calidad',
            value_2_text: 'Solo los mejores materiales.',
            value_3_title: 'Comunidad',
            value_3_text: 'Para quienes ven diferente.',
        },
        cart: {
            title: 'Bolsa de Compras',
            empty: 'Tu bolsa está vacía',
            subtotal: 'Subtotal',
            checkout: 'Pagar',
            back: 'Volver a Comprar',
            items_count: 'artículos',
            qty: 'Cant',
        },
        checkout: {
            title: 'Pago',
            shipping: 'Detalles de Envío',
            name: 'Nombre Completo',
            email: 'Correo Electrónico',
            address: 'Dirección',
            city: 'Ciudad',
            zip: 'Código Postal',
            payment: 'Detalles de Pago',
            card: 'Número de Tarjeta',
            expiry: 'Vencimiento',
            summary: 'Resumen del Pedido',
            btn_complete: 'Completar Compra',
        },
        search: {
            close: 'CERRAR',
            placeholder: 'Buscar ropa, colecciones, inspiración...',
            no_results: 'No se encontraron resultados para',
            trending: 'Tendencias',
        },
        footer: {
            follow: 'Síguenos',
            support: 'Soporte',
            shop: 'Tienda',
            privacy: 'Política de Privacidad',
            terms: 'Términos de Servicio',
            rights: 'Todos los derechos reservados. Construido para el futuro.',
            desc: 'Elevando la cultura pop a través de ropa premium. Diseñado para los audaces y creativos.',
            description: 'Elevando la cultura pop a través de ropa premium. Diseñado para los audaces y creativos.',
            shipping: 'Envíos',
            returns: 'Devoluciones',
            links: {
                shipping: 'Envíos',
                returns: 'Devoluciones',
                size_guide: 'Guía de Tallas',
                contact: 'Contacto',
            }
        },
        lookbook: {
            back: 'VOLVER AL INICIO',
            editorial: 'Editorial',
            the: 'LAS',
            chronicles: 'CRÓNICAS',
            subtitle: 'Un viaje visual curado a través de los lanzamientos más icónicos y narrativas estacionales de Visualmind.',
            look1: 'Verano en Línea',
            look2: 'Sombras de Otoño',
            look3: 'La Serie Goat',
            look4: 'Estética Underground',
            look5: 'Estilo Maldito',
            look6: 'Lanzamientos de San Valentín',
        },
        home_extended: {
            featured_drops: 'Lanzamientos Destacados',
            signature_pieces: 'Piezas de Autor',
            exclusive_release: 'LANZAMIENTO EXCLUSIVO',
            desc_prefix: 'Experimenta el lujo con nuestra colección insignia de',
            desc_suffix: '. Diseñado para quienes exigen excelencia en cada puntada.',
            btn_explore: 'Explorar Producto',
            limited_stock: 'STOCK LIMITADO',
            limited_time_drop: 'LANZAMIENTO POR TIEMPO LIMITADO',
            seasonal_specials: 'Especiales de Temporada',
            seasonal_desc: 'Colecciones exclusivas creadas para momentos especiales. Disponibles solo por unas semanas.',
            view_full_drop: 'Ver Colección Completa',
            visual_experience: 'Experiencia Visual',
            the_lookbook: 'El Lookbook',
            view_narratives: 'Ver Todas las Narrativas',
            style_01: 'ESTILO 01',
            seasonal_aura: 'Aura Estacional',
            quote: '"La moda es la armadura para sobrevivir a la realidad de la vida cotidiana."',
            since: 'Desde 2024',
            digital_heritage_1: 'Creando el',
            digital_heritage_2: 'Legado Digital',
            about_text: "En Visualmind, creemos que la ropa es más que tela: es un medio para la autoexpresión. Unimos la cultura digital y la realidad física a través de prendas meticulosamente elaboradas.",
            stat_1: 'ALGODÓN PREMIUM',
            stat_2: 'LANZAMIENTOS EXCLUSIVOS',
            stat_3: 'ENVÍOS INTERNACIONALES',
            join_universe: 'Únete al Universo',
            join_text: 'Suscríbete para obtener acceso anticipado a nuevos lanzamientos y ofertas exclusivas para miembros.',
            subscribe: 'Suscribirse',
        },
        shop_extended: {
            collections_group: 'Colecciones',
            seasonals_group: 'Estacionales',
            price_range: 'Rango de Precio',
            sizes: 'Tallas',
            colors: 'Colores',
            showing: 'Mostrando',
            of: 'de',
            products: 'productos',
            sort_by: 'Ordenar por:',
            sort_newest: 'Más Nuevos',
            sort_low_high: 'Precio: Menor a Mayor',
            sort_high_low: 'Precio: Mayor a Menor',
            no_results_text: "Intenta ajustar tus filtros para encontrar lo que buscas.",
            reset_filters: 'Restablecer Filtros',
        },
        auth: {
            welcome: 'Bienvenido',
            join: 'Únete a Visualmind',
            login_subtitle: 'Ingresa tus credenciales para acceder a tu cuenta',
            signup_subtitle: 'Crea una cuenta para seguir pedidos y guardar favoritos',
            email: 'Correo Electrónico',
            password: 'Contraseña',
            sign_in: 'Iniciar Sesión',
            sign_up: 'Registrarse',
            create_account: 'Crear Cuenta',
            no_account: "¿No tienes una cuenta?",
            has_account: "¿Ya tienes una cuenta?",
            success_create: '¡Cuenta creada! Ya has iniciado sesión.',
            error_generic: 'Ocurrió un error.',
        },
        profile: {
            title: 'Mi Cuenta',
            admin_access: 'Acceder al Panel Admin',
            sign_out: 'Cerrar Sesión',
            history: 'Historial de Pedidos',
            loading: 'Cargando pedidos...',
            no_orders: 'No se encontraron pedidos.',
            order_prefix: 'Pedido #',
            login_prompt: 'Por favor inicia sesión para ver tu perfil.',
            btn_login: 'Iniciar Sesión',
            edit_title: 'Editar Perfil',
            full_name: 'Nombre completo',
            email: 'Correo electrónico',
            save: 'Guardar cambios',
            saving: 'Guardando...',
            update_success: 'Perfil actualizado correctamente.',
            update_error: 'Error al actualizar el perfil.',
        },
        admin: {
            title: 'VM Admin',
            dashboard: 'Dashboard',
            products: 'Productos',
            orders: 'Pedidos',
            settings: 'Ajustes',
            overview: 'Resumen',
            user_label: 'Usuario Admin',
            access_denied: 'Acceso Denegado',
            denied_msg: 'No tienes permiso para ver esta área.',
            go_home: 'Ir al Inicio',
            log_out: 'Cerrar Sesión',
            starting: 'Iniciando Panel Admin...',
            // Dashboard
            stats_sales: 'Ventas Totales',
            stats_orders: 'Pedidos Activos',
            stats_customers: 'Clientes Totales',
            stats_rate: 'Tasa de Conversión',
            recent_orders: 'Pedidos Recientes',
            low_stock: 'Alerta de Stock Bajo',
            table_id: 'ID Pedido',
            table_customer: 'Cliente',
            table_date: 'Fecha',
            table_status: 'Estado',
            table_total: 'Total',
            table_items: 'Arts.',
            table_action: 'Acción',
            stock_left: 'Solo quedan {{count}}',
            // Products
            add_product: 'Añadir Producto',
            edit_product: 'Editar Producto',
            search_products: 'Buscar productos...',
            no_products: 'No se encontraron productos.',
            save_product: 'Guardar Producto',
            saving: 'Guardando...',
            confirm_delete: '¿Estás seguro de que quieres eliminar este producto?',
            label_title: 'Título del Producto',
            label_category: 'Categoría',
            label_subcategory: 'Subcategoría',
            label_sku: 'SKU',
            label_stock: 'Existencias',
            label_price: 'Precio',
            label_image: 'URL de Imagen',
            // Orders
            filter_pending: 'Pendiente',
            filter_shipped: 'Enviado',
            filter_delivered: 'Entregado',
            // Settings
            settings_title: 'Ajustes y Permisos',
            admin_mgmt: 'Gestión de Administradores',
            admin_desc: 'Otorgar acceso de administrador a otros usuarios.',
            promote_title: 'Promover Usuario a Admin',
            promote_desc: 'Ingresa el correo de un usuario registrado para darle acceso total.',
            promote_warn: 'Advertencia: Esto otorga control total.',
            promote_btn: 'Promover',
            success_promote: '¡Éxito! El usuario ahora es Admin.',
            user_not_found: 'Usuario no encontrado.',
            your_profile: 'Tu Perfil',
            role_label: 'Rol',
        },
        common: {
            loading: 'Cargando...',
            processing: 'Procesando...',
            success: 'Éxito',
            error: 'Error',
            secure_payment: 'Pago Seguro vía Stripe',
        },
        collections_page: {
            back: 'Volver a Colecciones',
            archive_title: 'Archivo Visualmind',
            curations: 'Curadurías',
            view_archive: 'Ver Archivo',
            limited_drop: 'LANZAMIENTO LIMITADO',
            anime_sub: 'El Alma del Arte Japonés',
            anime_desc: 'Explora nuestra selección curada de ropa inspirada en anime de alta gama. Cada pieza cuenta una historia de artesanía y pasión.',
            videojuegos_sub: 'Sube de Nivel tu Estética',
            videojuegos_desc: 'Donde la cultura gaming se encuentra con la moda de lujo. Diseñado para quienes aprecian el arte detrás de los píxeles.',
            halloween_title: 'Lanzamiento de Halloween',
            halloween_sub: 'Lanzamiento Estacional Limitado',
            halloween_desc: 'Una visión oscura y sofisticada de la ropa de temporada. Cada artículo es parte de una serie limitada numerada.',
            deportes_sub: 'Rendimiento de Élite, Estilo Urbano',
            deportes_desc: 'Uniendo la excelencia atlética y la sofisticación callejera.',
        },
        new_arrivals_page: {
            seasonal_active: 'LANZAMIENTOS DE TEMPORADA ACTIVOS',
            next_gen: 'Siguiente Generación',
            desc: 'La última evolución de Visualmind. Piezas limitadas, estilo infinito.',
            fresh_in: 'Recién Llegado',
            items: 'ARTÍCULOS',
            archive_halloween: 'El Archivo: Halloween',
            limited_seasonal: 'Lanzamiento Estacional Limitado',
            expires: 'EXPIRA EN 14 DÍAS',
            coming_soon: 'PRÓXIMAMENTE EL PRÓXIMO MES',
            winter_series: 'La Serie Cyberpunk de Invierno',
            winter_desc: 'Actualmente estamos finalizando la colección más ambiciosa en la historia de Visualmind. Telas de alta tecnología encuentran siluetas vanguardistas.',
        },
        wishlist_page: {
            empty_title: 'Tu lista de deseos está vacía',
            empty_desc: 'Guarda tus artículos favoritos aquí para no perderlos de vista.',
            explore: 'Explorar Tienda',
            title: 'Lista de Deseos',
            count_text: 'Tienes {{count}} artículos guardados en tu lista.',
        },
        search_modal: {
            trending_items: ['Abrigos', 'Tejidos', 'Esenciales'],
        }
    }
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('es');

    const t = (path) => {
        const keys = path.split('.');
        let result = translations[lang];
        for (const key of keys) {
            if (result[key]) {
                result = result[key];
            } else {
                return path; // Fallback to path if key not found
            }
        }
        return result;
    };

    const toggleLanguage = () => {
        setLang(prev => prev === 'en' ? 'es' : 'en');
    };

    return (
        <LanguageContext.Provider value={{ lang, language: lang, setLang, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
